name: Autograding Tests
'on':
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
    - name: testFarmerToString
      id: testfarmertostring
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: testFarmerToString
        setup-command: ''
        command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "FarmerTest.testToString"
        timeout: 10
        max-score: 3
    - name: testFarmerEquals
      id: testfarmerequals
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: testFarmerEquals
        setup-command: ''
        command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "FarmerTest.testEquals"
        timeout: 10
        max-score: 3
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TESTFARMERTOSTRING_RESULTS: "${{steps.testfarmertostring.outputs.result}}"
        TESTFARMEREQUALS_RESULTS: "${{steps.testfarmerequals.outputs.result}}"
      with:
        runners: testfarmertostring,testfarmerequals
